# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: referee_command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15referee_command.proto\x12\x0freferee_command\"G\n\x0fReferee_Command\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nyellowteam\x18\x02 \x01(\x08\x12\x11\n\tpacket_id\x18\x03 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'referee_command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REFEREE_COMMAND._serialized_start=42
  _REFEREE_COMMAND._serialized_end=113
# @@protoc_insertion_point(module_scope)
