# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: referee_command.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='referee_command.proto',
  package='referee_command',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15referee_command.proto\x12\x0freferee_command\"G\n\x0fReferee_Command\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nyellowteam\x18\x02 \x01(\x08\x12\x11\n\tpacket_id\x18\x03 \x01(\rb\x06proto3'
)




_REFEREE_COMMAND = _descriptor.Descriptor(
  name='Referee_Command',
  full_name='referee_command.Referee_Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready', full_name='referee_command.Referee_Command.ready', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yellowteam', full_name='referee_command.Referee_Command.yellowteam', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_id', full_name='referee_command.Referee_Command.packet_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Referee_Command'] = _REFEREE_COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Referee_Command = _reflection.GeneratedProtocolMessageType('Referee_Command', (_message.Message,), {
  'DESCRIPTOR' : _REFEREE_COMMAND,
  '__module__' : 'referee_command_pb2'
  # @@protoc_insertion_point(class_scope:referee_command.Referee_Command)
  })
_sym_db.RegisterMessage(Referee_Command)


# @@protoc_insertion_point(module_scope)
